---
          - name: Mise à jour des paquets
            apt:
                    update_cache: yes
                    upgrade: yes

          - name: Installation des paquets
            apt:
                    name: "{{ item }}"
                    state: present
            loop: "{{ paquets }}"
            notify: Lancer Mariadb
          
          - name: Déclencher les handlers
            meta: flush_handlers
